version: '3'
services:

  mariadb:
    image: mariadb:10.6.1
    container_name: mariadb-container
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "common_app"
    volumes:
      - ./.volumes/database:/var/lib/mysql

  api:
    build: ./
    links:
      - mariadb
    depends_on:
      - mariadb
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_URL: "mariadb:3306/common_app"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"

