version: '3'
services:

  database:
    image: postgres:13
    restart: unless-stopped
    container_name: common-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data

  api:
    image: common-api:4.1.1
    restart: unless-stopped
    container_name: common-api
    links:
      - database
    ports:
      - 8080:80
    environment:
      DB_URL: database:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_SHOW_SQL: "false"
      PRIVATE_SWAGGER: "true"
