version: '3'
services:
  
  database:
    image: postgres:13
    restart: unless-stopped
    container_name: common-database
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - ./.volumes/database:/var/lib/postgresql/data
  
  api:
    image: maven:3.8.3
    restart: unless-stopped
    container_name: common-api
    links:
      - postgresql
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      DB_URL: database:5432/${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/app
      - ./.volumes/maven:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run