name: CI/CD STAGING

on:
  workflow_dispatch:
  
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Deploy in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOSTNAME }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          port: 22
          script: |
            DOCKER_BUILDKIT=1
            cd /home/ubuntu/repository
            git checkout develop -f
            git fetch
            git pull
            docker build -t spring-crud-api:development .
            cd /home/ubuntu
            docker-compose up -d --build