name: CI/CD STAGING

on:
  workflow_dispatch:
  
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚀 Deploy in EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOSTNAME }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          port: 22
          script: |
            echo "🔨 updating repository"
            cd /home/ubuntu/repository
            eval `ssh-agent -s`
            ssh-add ~/.ssh/github_action
            git checkout development -f
            git fetch
            git pull
            echo " "
            echo "📦 building docker image"
            DOCKER_BUILDKIT=1 docker build -t spring-crud-api:development .
            echo " "
            echo "🚨 restarting container"
            cd /home/ubuntu
            docker-compose up -d --force-recreate
            echo " "            
            echo "🚀 deploy finished"